services:
  postgres:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  redis:
    image: redis:7.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: 'redis-server --requirepass "$REDIS_PASSWORD"'
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  raas:
    platform: "linux/amd64"
    build:
      context: ./build/raas
      args:
        filename: ${RAAS_RPM_NAME}
    command: "-l debug"
    ports:
      - "8080:8080"
    volumes:
      - ./data/raas:/etc/raas
    depends_on:
      - postgres
      - redis
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  salt-master:
    platform: "linux/amd64"
    hostname: salt-master
    build:
      context: ./build/salt-master
      args:
        salt_version: ${SALT_VERSION}
        plugin_name: ${MASTER_PLUGIN_NAME}
    command: "-l debug"
    volumes:
      - ./data/master.d:/etc/salt/master.d
      - ./data/srv-salt:/srv/salt
      - ./data/srv-pillar:/srv/pillar
    depends_on:
      - salt-minion-ubuntu
      - salt-minion-centos
      - salt-minion-debian
      - salt-minion-fedora
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  salt-minion-ubuntu:
    build:
      context: ./build/salt-minion-ubuntu
      args:
        salt_version: ${SALT_VERSION}
    command: "-l debug"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/minion.d:/etc/salt/minion.d
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  salt-minion-centos:
    build:
      context: ./build/salt-minion-centos
      args:
        salt_version: ${SALT_VERSION}
    command: "-l debug"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/minion.d:/etc/salt/minion.d
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  salt-minion-debian:
    build:
      context: ./build/salt-minion-debian
      args:
        salt_version: ${SALT_VERSION}
    command: "-l debug"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/minion.d:/etc/salt/minion.d
    logging:
      options:
        max-size: "200k"
        max-file: "5"

  salt-minion-fedora:
    build:
      context: ./build/salt-minion-fedora
      args:
        salt_version: ${SALT_VERSION}
    command: "-l debug"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data/minion.d:/etc/salt/minion.d
    logging:
      options:
        max-size: "200k"
        max-file: "5"
